#自定义配置
#family:
#  family-name: happy family
#  father:
#    name: tom
#    age: 23
#    email: 123@123.com
#    #${random.int(40)}
#    #爸爸的年龄是40以内的整数
#  mother:
#    alias:
#      - rose
#      - alice
#  child:
#    name: jack
#    age: 6
#    firends:
#      - hobby: football
#        gender: male
#      - hobby: sing
#        gender: female
#        下面这个配置与上面相同
#     -{ hobby: football,
#        gender: male}
#     -{hobby: sing,
#        gender: female}

##指定需要使用的文件
#spring:
#  profiles:
#    active: test
#server:
#  port: 8888
erver:
  port: 8080
spring:
  # 数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 这里加上后缀用来防止mysql乱码,serverTimezone=GMT%2b8设置时区
    url: ENC(h20YiPrvNnuuTGjlrE1RVpudMuIQAS6ZPSVo1SPiYVyLen7/TWI5rXVRkStA3MDcoVHQCmLa70wYU6Qo8wwtnsmaXa5jykD3MNhAp5SGJxHsTG5u7tflPdnNmOufyhdsYPxBGWAgibYs9R7yBfrvtwBTRbe096APd3bnG3++Yro=)
    username: ENC(sT6BztXbJEa71eg3pPGYMQ==)
    password: ENC(MpSZFJ9ftq+3+VUANZjr0Q==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 返回的api接口的配置，全局有效
  jackson:
    # 如果某一个字段为null，就不再返回这个字段
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    time-zone: GMT+8
# jasypt加密的密匙
jasypt:
  encryptor:
    password: Y6M9fAJQdU7jNp5MW